keys:
  - &users:
    - &coldelectrons age1u6selkqf5328c5wfm0zycwncku8jaq503eqw7p93a53w4fteyvfstp0rl7
  - &hosts:
    - &stickers age1x0a8ukg2dzfvvsydgpk7s0h9tmmrasha0upve80p5u9emsh9afdq99r9ye

creation_rules:
  - path_regex: hosts/stickers/secrets.yaml$
    key_groups:
    - age:
      - *coldelectrons
      - *stickers
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
    - age:
      - *coldelectrons
      - *stickers
  - path: secrets.yaml
    key_groups:
    - age:
      - *coldelectrons
      - *stickers
